//created on: 01-Jul-2019
import com.sample.Clientes;
import com.sample.Items;
import com.sample.Fatura;
import java.util.Scanner;



//declare any global variables here

//REGRA 1 IDENTIFICAR CLIENTE

rule "Deseja comprar algo?"
	salience 90
	then
		char resposta;
		System.out.println("Deseja escolher algum item da lista? (S/N)");
		Scanner ler = new Scanner(System.in);
        resposta = (char)System.in.read();
		
		if(resposta == 'N')
        {
        	System.out.println("Obrigado pela sua visita!");
        	System.exit(0);
        }
        if(resposta == 'S')
        {
        
        	//criar fatura nova
        	insert ( new Fatura(0,0) );
        	
        }	
end

rule "Mostrar items disponíveis"
	salience 80
	when
		exists Fatura()
		$i:Items( ( sexo == "masculino" || sexo == "feminino" ) && stock > 0)		
	then		
		System.out.println("Item " + $i.getId() + ": " + $i.getNome() + " (para " + $i.getTipo() + ", " + $i.getSexo() + ")" + ", preço: " + $i.getPreco());        	
end

rule "Escolher Item"
	salience 70
	agenda-group "EscolherItem"
	when
		exists Fatura()
	then		
		int id;
		System.out.printf("Informe um Número Inteiro: ");
		Scanner ler = new Scanner(System.in);
		id = ler.nextInt();
			
end

rule "Escolher Mais?"
	salience 60
	when
		exists Fatura()
	then		
		char resposta;
		System.out.println("Deseja escolher mais items da lista? (S/N)");
		Scanner ler = new Scanner(System.in);
        resposta = (char)System.in.read();
		
		if(resposta == 'N')
        {
        	// FINALIZAR COMPRA
        }
        if(resposta == 'S')
        {
        
        	drools.setFocus("EscolherItem");
        	
        }
			
end

/*
rule "Clientes Masculinos"
    when
    	$c:Clientes( sexo == "masculino" )
    then
        //System.out.println("Nome do Cliente: " + $c.getNome());
end
*/

